FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake libz-dev libbz2-dev

COPY . /repo
WORKDIR /repo/assembler
RUN chmod +x spades_compile.sh
RUN ./spades_compile.sh

FROM ubuntu:22.04 as package
COPY --from=builder /repo/assembler/bin/spades-bwa /
