FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libz-dev libbz2-dev

COPY . /repo
WORKDIR /repo/assembler
RUN chmod +x spades_compile.sh
RUN ./spades_compile.sh
